image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  # параметр -P:profile=test активирует тестовый режим при запуске SUT
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

build_script:
  - chmod +x gradlew    # предоставление прав на запуск файла gradlew
  # запуск тестов, параметр -Dselenide.headless=true отключает графический интерфейс
  # запускаем тест, флаг --info позволяет выводить больше информации
  - ./gradlew test -Dselenide.headless=true --info